# Spring profiles can be used to segregate parts of your application configuration and make it only available in certain environments.
# The active profile is set in build.gradle for local runs and can be overridden with environment variables in higher environments.
spring:
  profiles:
    active: dev # Default to dev profile
