package com.redis.poc.controller;

import com.redis.poc.streams.OrderEvent;
import com.redis.poc.streams.OrderEventProducer;
import org.springframework.data.redis.connection.stream.RecordId;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Map;

/**
 * REST controller for demonstrating Redis Streams functionality.
 * It provides an endpoint to publish order events to a stream.
 */
@RestController
@RequestMapping("/api/streams")
public class StreamController {

    private final OrderEventProducer orderEventProducer;

    public StreamController(OrderEventProducer orderEventProducer) {
        this.orderEventProducer = orderEventProducer;
    }

    /**
     * Endpoint to publish a new order event to the Redis Stream.
     * It accepts an OrderEvent object and passes it to the producer service.
     *
     * Best Practice: The response includes the unique message ID generated by Redis for the stream entry.
     * This allows the client to track the event or correlate it with other processes.
     *
     * @param event The order event from the request body to be published.
     * @return A ResponseEntity containing a map with the publishing status and the unique message ID.
     */
    @PostMapping("/publish")
    public ResponseEntity<Map<String, String>> publishOrderEvent(@RequestBody OrderEvent event) {
        RecordId recordId = orderEventProducer.publishOrderEvent(event);
        return ResponseEntity.ok(Map.of(
                "status", "event published",
                "messageId", recordId.getValue()
        ));
    }
}
